/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DarknetTest */

#ifndef _Included_DarknetTest
#define _Included_DarknetTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DarknetTest
 * Method:    Detect
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_DarknetTest_Detect
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
