/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xikuiw_volcano_hermit_analyzer_ObjectDetector */

#ifndef _Included_xikuiw_volcano_hermit_analyzer_ObjectDetector
#define _Included_xikuiw_volcano_hermit_analyzer_ObjectDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xikuiw_volcano_hermit_analyzer_ObjectDetector
 * Method:    GetDarknetObjectBounds
 * Signature: (Ljava/lang/String;)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_xikuiw_volcano_hermit_analyzer_ObjectDetector_GetDarknetObjectBounds
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
